version: '3.4'

services:
  vendingmachine-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - "5000:5000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  vendingmachine-api-seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
  
  postgres:
    environment:
      POSTGRES_PASSWORD: sa
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
      - ./docker-data/postgres-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lev4and.ru
      PGADMIN_DEFAULT_PASSWORD: sa
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
    volumes:
      - ./docker-data/pgadmin:/var/lib/pgadmin
  
  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"